version: "2"
run:
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - gochecknoinits
    - goprintffuncname
    - lll
    - misspell
    - nakedret
    - nolintlint
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  disable:
    - dupl
    - gochecknoglobals
    - gocritic
    - godot
    - godox
    - nestif
    - prealloc
    - testpackage
    - wsl
  settings:
    gocyclo:
      min-complexity: 15
    misspell:
      locale: US
    unparam:
      check-exported: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - funlen
          - mnd
        path: _test\.go
      - linters:
          - staticcheck
        text: 'SA9003:'
      - linters:
          - lll
        source: '^//go:generate '
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - gofumpt
    - golines
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/n1rna/ee-cli
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
